<?php

########################################################################
# Extension Manager/Repository config file for ext: "www.zarges.com"
#
# Auto generated by Extension Builder 2012-04-26
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'bgm hreflang',
	'description' => 'An extension to add hreflang meta tags. Page translations are added automatically as hreflang tags. Editors can configure other pages in the page properties which should be added as hreflang tags.',
	'category' => 'Plugin',
	'author' => 'bgm websolutions GmbH & Co. KG',
	'author_email' => 'typo3@bgm-gmbh.de',
	'author_company' => 'bgm websolutions GmbH & Co. KG',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0.0-6.2.9999',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>